---
- name: restart unifi
  service:
    name: "{{ item }}"
    state: restarted
  become: yes
  with_items: "{{ unifi_services }}"

- name: restart mongodb
  service:
    name: "{{ item }}"
    state: restarted
  become: yes
  with_items: "{{ unifi_mongodb_services }}"
