---

  - name: ensure the monngo apt key is present
    apt_key:
      url: "https://www.mongodb.org/static/pgp/server-3.6.asc"
      state: present

  - name: "[Debian] ensure the mongodb is present (have to use stretch repo for MondoDB 3.x due to ubiquiti not updating their support for MongoDB)"
    apt_repository:
      repo: "deb http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} stretch/mongodb-org/{{ mongodb_version }} main"
      state: present
      filename: "mongodb-{{ mongodb_version }}"
    when: ansible_distribution == "Debian"

  - name: "[Ubuntu] ensure the mongodb is present (have to use xenial repo for MondoDB 3.x due to ubiquiti not updating their support for MongoDB)"
    apt_repository:
      repo: "deb http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} xenial/mongodb-org/{{ mongodb_version }} multiverse"
      state: present
      filename: "mongodb-{{ mongodb_version }}"
    when: ansible_distribution == "Ubuntu"

  - name: "[Ubuntu] ensure libssl 1.0.0 is present (dep for MongoDB)"
    apt:
      deb: http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
    when: ansible_distribution == "Ubuntu"

  - name: "ensure mondo db {{ mongodb_version }} is present"
    apt:
      name: mongodb-org
      state: present
      update_cache: yes

  - name: ensure the systemd service is reload and the mongod service has started
    ansible.builtin.systemd:
      state: started
      daemon_reload: yes
      name: mongod

  - name: ensure the mongod service is enabled
    ansible.builtin.systemd:
      enabled: yes
      name: mongod
